// ── plumbus agent ──
// AI agent management: brief, sync

import type { Command } from "commander";
import * as path from "node:path";
import type { CapabilityContract } from "../../types/capability.js";
import type { EntityDefinition } from "../../types/entity.js";
import type { EventDefinition } from "../../types/event.js";
import type { FlowDefinition } from "../../types/flow.js";
import type { PromptDefinition } from "../../types/prompt.js";
import { discoverResources } from "../discover.js";
import { info, success, warn, writeFile } from "../utils.js";
import { writeAgentFiles } from "./init.js";

export interface BriefOptions {
  json?: boolean;
}

/** Generate a capability brief for AI agents */
export function generateCapabilityBrief(cap: CapabilityContract): string {
  const lines = [
    `# Capability: ${cap.name}`,
    "",
    `**Domain**: ${cap.domain}`,
    `**Kind**: ${cap.kind}`,
    cap.description ? `**Description**: ${cap.description}` : "",
    "",
    "## Access Policy",
    cap.access
      ? `- Roles: ${cap.access.roles?.join(", ") || "none"}`
      : "- No access policy defined",
    cap.access?.scopes?.length
      ? `- Scopes: ${cap.access.scopes.join(", ")}`
      : "",
    cap.access?.tenantScoped ? "- Tenant-scoped: yes" : "",
    "",
    "## Effects",
    `- Data: ${cap.effects.data?.join(", ") || "none"}`,
    `- Events: ${cap.effects.events?.join(", ") || "none"}`,
    `- External: ${cap.effects.external?.join(", ") || "none"}`,
    `- AI: ${cap.effects.ai ? "yes" : "no"}`,
    "",
    "## Testing Requirements",
    "- Unit test handler logic with `createTestContext()`",
    "- Test access control with unauthorized auth context",
    "- Test input validation with invalid payloads",
    cap.effects.events?.length ? "- Verify events are emitted correctly" : "",
    cap.effects.ai ? "- Mock AI responses with `mockAI()`" : "",
    "",
  ];
  return lines.filter(Boolean).join("\n");
}

/** Generate an entity brief for AI agents */
export function generateEntityBrief(entity: EntityDefinition): string {
  const fieldLines = Object.entries(entity.fields).map(
    ([name, def]) => `  - \`${name}\`: ${def.type}${def.options.classification ? ` (${def.options.classification})` : ""}`,
  );
  return [
    `# Entity: ${entity.name}`,
    "",
    `**Tenant-scoped**: ${entity.tenantScoped ? "yes" : "no"}`,
    "",
    "## Fields",
    ...fieldLines,
    "",
  ].join("\n");
}

/** Generate a project brief from discovered resources */
export function generateProjectBriefFromResources(
  capabilities: CapabilityContract[],
  entities: EntityDefinition[],
  flows: FlowDefinition[],
  events: EventDefinition[],
  prompts: PromptDefinition[],
): string {
  const lines = [
    "# Project Brief",
    "",
    "> Auto-generated by `plumbus agent sync`.",
    "",
    "## Registered Resources",
    "",
    `### Entities (${entities.length})`,
    ...entities.map((e) => `- **${e.name}**${e.tenantScoped ? " (tenant-scoped)" : ""}`),
    "",
    `### Capabilities (${capabilities.length})`,
    ...capabilities.map((c) => `- **${c.name}** (${c.kind}, domain: ${c.domain})`),
    "",
    `### Flows (${flows.length})`,
    ...flows.map((f) => `- **${f.name}** (domain: ${f.domain}, ${f.steps.length} steps)`),
    "",
    `### Events (${events.length})`,
    ...events.map((e) => `- **${e.name}**`),
    "",
    `### Prompts (${prompts.length})`,
    ...prompts.map((p) => `- **${p.name}**`),
    "",
  ];
  return lines.join("\n");
}

export function registerAgentCommand(program: Command): void {
  const cmd = program.command("agent").description("AI agent management");

  cmd
    .command("brief <resource> <name>")
    .description("Generate AI-agent-friendly documentation for a resource")
    .option("--json", "Output as JSON")
    .action(async (resource: string, name: string, opts: BriefOptions) => {
      info(`Generating brief for ${resource}: ${name}`);

      let brief: string | null = null;
      try {
        const resources = await discoverResources();
        if (resource === "capability") {
          const cap = resources.capabilities.find((c) => c.name === name);
          if (cap) brief = generateCapabilityBrief(cap);
        } else if (resource === "entity") {
          const entity = resources.entities.find((e) => e.name === name);
          if (entity) brief = generateEntityBrief(entity);
        }
      } catch {
        // discovery failed
      }

      if (brief) {
        if (opts.json) {
          console.log(JSON.stringify({ resource, name, brief }, null, 2));
        } else {
          console.log(brief);
        }
      } else {
        if (opts.json) {
          console.log(JSON.stringify({ resource, name, brief: "Resource not found" }, null, 2));
        } else {
          console.log(`Brief for ${resource} "${name}" — resource not found in app/.`);
          info("Register the resource first, then run `plumbus agent brief` again.");
        }
      }
    });

  cmd
    .command("sync")
    .description("Regenerate project brief and update agent config files")
    .action(async () => {
      info("Syncing project brief...");

      const projectRoot = process.cwd();

      let capabilities: CapabilityContract[] = [];
      let entities: EntityDefinition[] = [];
      let flows: FlowDefinition[] = [];
      let events: EventDefinition[] = [];
      let prompts: PromptDefinition[] = [];
      try {
        const resources = await discoverResources(projectRoot);
        capabilities = resources.capabilities;
        entities = resources.entities;
        flows = resources.flows;
        events = resources.events;
        prompts = resources.prompts;
        info(`Discovered ${capabilities.length} capabilities, ${entities.length} entities, ${flows.length} flows, ${events.length} events, ${prompts.length} prompts`);
      } catch {
        warn("Could not auto-discover resources (app/ directory may not exist)");
      }

      const brief = generateProjectBriefFromResources(capabilities, entities, flows, events, prompts);
      const briefPath = path.join(projectRoot, ".plumbus", "briefs", "project.md");
      writeFile(briefPath, brief);
      success("Updated .plumbus/briefs/project.md");

      // Re-run init to update agent config files
      writeAgentFiles(projectRoot, ["copilot", "cursor", "agents-md"], false);
      success("Updated agent configuration files");
    });
}
