// ── plumbus generate ──
// Auto-generate derived artifacts from contracts

import type { Command } from 'commander';
import * as path from 'node:path';
import type { CapabilityContract } from '../../types/capability.js';
import type { CapabilityKind } from '../../types/enums.js';
import { discoverResources } from '../discover.js';
import {
  info,
  resolvePath,
  success,
  toCamelCase,
  toKebabCase,
  toPascalCase,
  warn,
  writeFile,
} from '../utils.js';

export interface GenerateOptions {
  json?: boolean;
}

/** Generate a typed API client function for a capability */
export function generateClientFunction(cap: CapabilityContract): string {
  const fnName = toCamelCase(cap.name);
  const kind = cap.kind as CapabilityKind;
  const method = kind === 'query' ? 'GET' : 'POST';
  const urlPath = `/api/${cap.domain}/${toKebabCase(cap.name)}`;

  return `export async function ${fnName}(input: ${toPascalCase(cap.name)}Input): Promise<${toPascalCase(cap.name)}Output> {
  const response = await fetch("${urlPath}", {
    method: "${method}",
    headers: { "Content-Type": "application/json" },
    body: ${method === 'GET' ? 'undefined' : 'JSON.stringify(input)'},
  });
  if (!response.ok) throw new Error(\`Request failed: \${response.status}\`);
  return response.json() as Promise<${toPascalCase(cap.name)}Output>;
}`;
}

/** Generate a React hook for a capability */
export function generateReactHook(cap: CapabilityContract): string {
  const hookName = `use${toPascalCase(cap.name)}`;
  const fnName = toCamelCase(cap.name);
  const kind = cap.kind as CapabilityKind;

  if (kind === 'query') {
    return `export function ${hookName}(input: ${toPascalCase(cap.name)}Input) {
  const [data, setData] = useState<${toPascalCase(cap.name)}Output | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    setLoading(true);
    ${fnName}(input).then(setData).catch(setError).finally(() => setLoading(false));
  }, [JSON.stringify(input)]);

  return { data, loading, error };
}`;
  }

  return `export function ${hookName}() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = async (input: ${toPascalCase(cap.name)}Input) => {
    setLoading(true);
    setError(null);
    try {
      return await ${fnName}(input);
    } catch (e) {
      setError(e instanceof Error ? e : new Error(String(e)));
      throw e;
    } finally {
      setLoading(false);
    }
  };

  return { mutate, loading, error };
}`;
}

/** Generate an OpenAPI path entry for a capability */
export function generateOpenApiPath(cap: CapabilityContract): Record<string, unknown> {
  const kind = cap.kind as CapabilityKind;
  const method = kind === 'query' ? 'get' : 'post';
  const urlPath = `/api/${cap.domain}/${toKebabCase(cap.name)}`;

  return {
    [urlPath]: {
      [method]: {
        operationId: cap.name,
        summary: cap.description ?? cap.name,
        tags: [cap.domain],
        requestBody:
          method === 'post'
            ? {
                required: true,
                content: { 'application/json': { schema: { type: 'object' } } },
              }
            : undefined,
        responses: {
          '200': {
            description: 'Successful response',
            content: { 'application/json': { schema: { type: 'object' } } },
          },
        },
      },
    },
  };
}

/** Generate a manifest entry for a capability */
export function generateManifestEntry(cap: CapabilityContract): Record<string, unknown> {
  return {
    name: cap.name,
    kind: cap.kind,
    domain: cap.domain,
    description: cap.description,
    effects: cap.effects,
    access: cap.access,
  };
}

/** Run full code generation for a set of capabilities */
export function generateAll(capabilities: CapabilityContract[], outputDir: string): string[] {
  const generated: string[] = [];

  // Client functions
  const clientLines = [
    '// Auto-generated by `plumbus generate` — do not edit',
    '',
    ...capabilities.map(generateClientFunction),
  ];
  writeFile(path.join(outputDir, 'clients', 'api.ts'), clientLines.join('\n\n'));
  generated.push('clients/api.ts');

  // React hooks
  const hookLines = [
    '// Auto-generated by `plumbus generate` — do not edit',
    '// eslint-disable-next-line @typescript-eslint/no-unused-vars',
    'import { useState, useEffect } from "react";',
    '',
    ...capabilities.map(generateReactHook),
  ];
  writeFile(path.join(outputDir, 'clients', 'hooks.ts'), hookLines.join('\n\n'));
  generated.push('clients/hooks.ts');

  // OpenAPI spec
  const paths: Record<string, unknown> = {};
  for (const cap of capabilities) {
    Object.assign(paths, generateOpenApiPath(cap));
  }
  const openApi = {
    openapi: '3.0.3',
    info: { title: 'Plumbus API', version: '0.1.0' },
    paths,
  };
  writeFile(path.join(outputDir, 'openapi.json'), JSON.stringify(openApi, null, 2));
  generated.push('openapi.json');

  // Manifest
  const manifest = {
    version: '0.1.0',
    generatedAt: new Date().toISOString(),
    capabilities: capabilities.map(generateManifestEntry),
  };
  writeFile(path.join(outputDir, 'manifest.json'), JSON.stringify(manifest, null, 2));
  generated.push('manifest.json');

  return generated;
}

export function registerGenerateCommand(program: Command): void {
  program
    .command('generate')
    .description(
      'Generate derived artifacts from contracts (API clients, hooks, OpenAPI, manifest)',
    )
    .option('--json', 'Output results as JSON')
    .action(async (opts: GenerateOptions) => {
      const outputDir = resolvePath('.plumbus', 'generated');

      info('Scanning for registered capabilities...');
      let capabilities: CapabilityContract[] = [];
      try {
        const resources = await discoverResources();
        capabilities = resources.capabilities;
        if (capabilities.length > 0) {
          info(`Discovered ${capabilities.length} capability(ies)`);
        } else {
          warn('No capabilities found in app/capabilities/');
        }
      } catch {
        warn('Could not auto-discover resources (app/ directory may not exist)');
      }

      const generated = generateAll(capabilities, outputDir);

      if (opts.json) {
        console.log(JSON.stringify({ generated }, null, 2));
      } else {
        for (const f of generated) {
          success(`Generated .plumbus/generated/${f}`);
        }
      }
    });
}
