// ── plumbus init ──
// Generate AI agent wiring files that connect coding agents to framework knowledge

import type { Command } from 'commander';
import * as path from 'node:path';
import { info, success, writeFile } from '../utils.js';

export type AgentFormat = 'copilot' | 'cursor' | 'agents-md';

export interface InitOptions {
  agent?: string;
  inline?: boolean;
}

const CORE_INSTRUCTION_TOPICS = [
  'framework',
  'cli',
  'capabilities',
  'flows',
  'entities',
  'events',
  'ai',
  'security',
  'governance',
  'testing',
  'patterns',
] as const;

const UI_INSTRUCTION_REFERENCES = [
  {
    area: 'frontend/ui generation',
    path: 'node_modules/@plumbus/ui/instructions/framework.md',
  },
  {
    area: 'typed clients and hooks',
    path: 'node_modules/@plumbus/ui/instructions/client-generator.md',
  },
  {
    area: 'auth helpers',
    path: 'node_modules/@plumbus/ui/instructions/auth-generator.md',
  },
  {
    area: 'form metadata generation',
    path: 'node_modules/@plumbus/ui/instructions/form-generator.md',
  },
  {
    area: 'Next.js frontend scaffolding',
    path: 'node_modules/@plumbus/ui/instructions/nextjs-template.md',
  },
  {
    area: 'frontend test coverage',
    path: 'node_modules/@plumbus/ui/instructions/testing.md',
  },
  {
    area: 'frontend generation patterns',
    path: 'node_modules/@plumbus/ui/instructions/patterns.md',
  },
] as const;

function addInstructionReferenceLines(lines: string[], inline: boolean): void {
  if (inline) {
    lines.push(
      'Refer to the bundled framework and UI instruction files in this project for full SDK documentation.',
    );
    return;
  }

  for (const topic of CORE_INSTRUCTION_TOPICS) {
    lines.push(
      `- When working on ${topic}, read \`node_modules/plumbus-core/instructions/${topic}.md\``,
    );
  }

  for (const reference of UI_INSTRUCTION_REFERENCES) {
    lines.push(`- When working on ${reference.area}, read \`${reference.path}\``);
  }
}

/** Generate the copilot-instructions.md content */
export function generateCopilotInstructions(inline: boolean): string {
  const lines = [
    '# Plumbus Framework — Copilot Instructions',
    '',
    'This project is built with the Plumbus framework — an AI-native, contract-driven TypeScript framework.',
    '',
    '## Key Conventions',
    '- Business logic lives in `app/capabilities/<domain>/<name>/`',
    '- Data models in `app/entities/`',
    '- Workflows in `app/flows/<domain>/<name>/`',
    '- Events in `app/events/`',
    '- AI prompts in `app/prompts/`',
    '- Config in `config/`',
    '',
    '## Edit Zones',
    '- **Safe**: `app/` directory (capabilities, entities, flows, events, prompts), `config/`, tests',
    '- **Restricted**: `.plumbus/` generated files (regenerated by CLI)',
    '- **Forbidden**: `node_modules/`, `dist/`',
    '',
    '## CLI Scaffolding',
    '**Always run CLI commands from the project root**. Use the Plumbus CLI to scaffold new primitives and UI artifacts:',
    '```',
    'plumbus entity new <EntityName>',
    'plumbus capability new <CapabilityName>',
    'plumbus event new <EventName>',
    'plumbus flow new <FlowName>',
    'plumbus prompt new <PromptName>',
    'plumbus ui generate',
    'plumbus ui nextjs <output-dir>',
    '```',
    'After scaffolding, fill in the `// TODO` sections in the generated files.',
    '',
    '## SDK Reference',
  ];

  addInstructionReferenceLines(lines, inline);

  lines.push(
    '',
    '## Project Brief',
    'See `.plumbus/briefs/project.md` for project-specific context.',
    '',
  );

  return lines.join('\n');
}

/** Generate the Cursor .mdc rule content */
export function generateCursorRule(inline: boolean): string {
  const lines = [
    '---',
    'description: Plumbus framework conventions and SDK reference',
    'globs: app/**',
    '---',
    '',
    '# Plumbus Framework',
    '',
    'This project uses the Plumbus framework for building AI-native, contract-driven applications.',
    '',
    '## Conventions',
    '- Capabilities: `app/capabilities/<domain>/<name>/`',
    '- Entities: `app/entities/<name>.entity.ts`',
    '- Flows: `app/flows/<domain>/<name>/`',
    '- Events: `app/events/<name>.event.ts`',
    '- Prompts: `app/prompts/<name>.prompt.ts`',
    '',
    '## Edit Zones',
    '- Safe: `app/`, `config/`, tests',
    '- Restricted: `.plumbus/generated/`',
    '- Forbidden: `node_modules/`, `dist/`',
    '',
    '## SDK Reference',
  ];

  addInstructionReferenceLines(lines, inline);

  lines.push('');
  return lines.join('\n');
}

/** Generate capability-specific Cursor rule */
export function generateCursorCapabilityRule(): string {
  return `---
description: Plumbus capability development rules
globs: app/capabilities/**
---

When creating or modifying capabilities:
- Use \`defineCapability()\` from plumbus-core
- Always declare effects (data, events, external, ai)
- Set access policies (deny-by-default)
- Use \`ctx.data\`, \`ctx.events\`, \`ctx.ai\` within handlers
- Reference: \`node_modules/plumbus-core/instructions/capabilities.md\`
`;
}

/** Generate AGENTS.md content */
export function generateAgentsMd(inline: boolean): string {
  const lines = [
    '# AGENTS.md — Plumbus Framework',
    '',
    'This project is built with the Plumbus framework.',
    '',
    '## Architecture',
    'AI-native, contract-driven TypeScript framework with primitives:',
    'Entities, Capabilities, Flows, Events, Prompts — composed through `ctx`.',
    '',
    '## Directory Structure',
    '- `app/capabilities/<domain>/<name>/` — Business logic',
    '- `app/entities/` — Data models',
    '- `app/flows/<domain>/<name>/` — Multi-step workflows',
    '- `app/events/` — Domain events',
    '- `app/prompts/` — AI prompt definitions',
    '- `config/` — App + AI configuration',
    '- `.plumbus/generated/` — Auto-generated (do not edit)',
    '',
    '## Edit Zones',
    '- **Safe**: `app/`, `config/`, tests',
    '- **Restricted**: `.plumbus/` (regenerated by `plumbus generate`)',
    '- **Forbidden**: `node_modules/`, `dist/`',
    '',
    '## SDK Reference',
  ];

  addInstructionReferenceLines(lines, inline);

  lines.push('');
  return lines.join('\n');
}

/** Generate the project brief */
export function generateProjectBrief(): string {
  return `# Project Brief

> Auto-generated by \`plumbus init\`. Update with \`plumbus agent sync\`.

## Registered Resources

- **Entities**: (run \`plumbus agent sync\` to populate)
- **Capabilities**: (run \`plumbus agent sync\` to populate)
- **Flows**: (run \`plumbus agent sync\` to populate)
- **Events**: (run \`plumbus agent sync\` to populate)
- **Prompts**: (run \`plumbus agent sync\` to populate)

## Configuration

- **Auth**: (detected at sync)
- **AI**: (detected at sync)
- **Compliance**: (detected at sync)

## Governance Warnings

None detected. Run \`plumbus verify\` to check.
`;
}

/** Write all files for a given agent format */
export function writeAgentFiles(
  projectRoot: string,
  formats: AgentFormat[],
  inline: boolean,
  includeProjectBrief = true,
): string[] {
  const written: string[] = [];

  for (const format of formats) {
    switch (format) {
      case 'copilot': {
        const filePath = path.join(projectRoot, '.github', 'copilot-instructions.md');
        writeFile(filePath, generateCopilotInstructions(inline));
        written.push('.github/copilot-instructions.md');
        break;
      }
      case 'cursor': {
        const mainRule = path.join(projectRoot, '.cursor', 'rules', 'plumbus.mdc');
        writeFile(mainRule, generateCursorRule(inline));
        written.push('.cursor/rules/plumbus.mdc');

        const capRule = path.join(projectRoot, '.cursor', 'rules', 'plumbus-capabilities.mdc');
        writeFile(capRule, generateCursorCapabilityRule());
        written.push('.cursor/rules/plumbus-capabilities.mdc');
        break;
      }
      case 'agents-md': {
        const filePath = path.join(projectRoot, 'AGENTS.md');
        writeFile(filePath, generateAgentsMd(inline));
        written.push('AGENTS.md');
        break;
      }
    }
  }

  if (includeProjectBrief) {
    const briefPath = path.join(projectRoot, '.plumbus', 'briefs', 'project.md');
    writeFile(briefPath, generateProjectBrief());
    written.push('.plumbus/briefs/project.md');
  }

  return written;
}

function parseAgentFormats(agent?: string): AgentFormat[] {
  if (!agent || agent === 'all') {
    return ['copilot', 'cursor', 'agents-md'];
  }
  const valid: AgentFormat[] = ['copilot', 'cursor', 'agents-md'];
  if (valid.includes(agent as AgentFormat)) {
    return [agent as AgentFormat];
  }
  return ['copilot', 'cursor', 'agents-md'];
}

export function registerInitCommand(program: Command): void {
  program
    .command('init')
    .description('Generate AI agent wiring files for the project')
    .option('--agent <format>', 'Agent format: copilot, cursor, all (default: all)')
    .option('--inline', 'Copy full instruction content instead of referencing node_modules')
    .action((opts: InitOptions) => {
      const projectRoot = process.cwd();
      const formats = parseAgentFormats(opts.agent);
      const written = writeAgentFiles(projectRoot, formats, opts.inline ?? false);

      for (const f of written) {
        success(`Created ${f}`);
      }

      info('Agent wiring complete. Run `plumbus agent sync` to populate project brief.');
    });
}
