// ── Next.js Project Template Generator ──
// Generates a Next.js project scaffold with Plumbus auth integration,
// generated client imports, and example pages wired to capabilities.

import type { CapabilityContract } from '@plumbus/core';

export interface NextjsTemplateConfig {
  /** Application name */
  appName: string;
  /** Whether to include auth wiring */
  auth?: boolean;
  /** Base URL for API calls */
  apiBaseUrl?: string;
}

// ── Helpers ──

function toPascalCase(str: string): string {
  return str.replace(/(^|[-_ ])(\w)/g, (_, _sep: string, c: string) => c.toUpperCase());
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

// ── File Generators ──

export interface GeneratedFile {
  path: string;
  content: string;
}

/** Generate package.json for the Next.js project */
export function generatePackageJson(config: NextjsTemplateConfig): GeneratedFile {
  const name = toKebabCase(config.appName);
  const content = JSON.stringify(
    {
      name,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
      },
      dependencies: {},
      devDependencies: {},
    },
    null,
    2,
  );

  return { path: 'package.json', content };
}

/** Generate tsconfig.json */
export function generateTsConfig(): GeneratedFile {
  const content = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        paths: {
          '@/*': ['./*'],
        },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
      exclude: ['node_modules'],
    },
    null,
    2,
  );

  return { path: 'tsconfig.json', content };
}

/** Generate globals.css with Tailwind import and basic resets */
export function generateGlobalsCss(): GeneratedFile {
  return {
    path: 'app/globals.css',
    content: `@import "tailwindcss";

/* ── Base resets ── */
*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  min-height: 100%;
}

body {
  margin: 0;
  min-height: 100vh;
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`,
  };
}

/** Generate postcss.config.mjs for Tailwind CSS */
export function generatePostcssConfig(): GeneratedFile {
  return {
    path: 'postcss.config.mjs',
    content: `export default {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n};\n`,
  };
}

/** Generate the layout component */
export function generateLayout(config: NextjsTemplateConfig): GeneratedFile {
  const auth = config.auth !== false;

  const authImport = auth ? `import { AuthProvider } from "../components/AuthProvider";\n` : '';
  const authWrapOpen = auth ? '        <AuthProvider>\n' : '';
  const authWrapClose = auth ? '        </AuthProvider>\n' : '';

  return {
    path: 'app/layout.tsx',
    content: `import type { Metadata } from "next";
import "./globals.css";
${authImport}
export const metadata: Metadata = {
  title: "${config.appName}",
  description: "Generated by @plumbus/ui",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
${authWrapOpen}          {children}
${authWrapClose}      </body>
    </html>
  );
}
`,
  };
}

/** Generate the home page */
export function generateHomePage(config: NextjsTemplateConfig): GeneratedFile {
  return {
    path: 'app/page.tsx',
    content: `export default function Home() {
  return (
    <main>
      <h1>${config.appName}</h1>
      <p>Welcome to your Plumbus application.</p>
    </main>
  );
}
`,
  };
}

/** Generate example page for a capability */
export function generateCapabilityPage(cap: CapabilityContract): GeneratedFile {
  const pascal = toPascalCase(cap.name);
  const slug = toKebabCase(cap.name);

  if (cap.kind === 'query') {
    return {
      path: `app/${slug}/page.tsx`,
      content: `"use client";

import { use${pascal} } from "@/hooks/hooks";

export default function ${pascal}Page() {
  const { data, loading, error } = use${pascal}({});

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <main>
      <h1>${cap.name}</h1>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </main>
  );
}
`,
    };
  }

  return {
    path: `app/${slug}/page.tsx`,
    content: `"use client";

import { use${pascal} } from "@/hooks/hooks";

export default function ${pascal}Page() {
  const { mutate, data, loading, error, reset } = use${pascal}();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const input = Object.fromEntries(formData.entries());
    await mutate(input as Record<string, unknown>);
  };

  return (
    <main>
      <h1>${cap.name}</h1>
      <form onSubmit={handleSubmit}>
        <button type="submit" disabled={loading}>
          {loading ? "Processing..." : "Submit"}
        </button>
      </form>
      {error && <p>Error: {error.message}</p>}
      {data && (
        <div>
          <pre>{JSON.stringify(data, null, 2)}</pre>
          <button onClick={reset}>Reset</button>
        </div>
      )}
    </main>
  );
}
`,
  };
}

/** Generate AuthProvider component */
export function generateAuthProvider(): GeneratedFile {
  return {
    path: 'components/AuthProvider.tsx',
    content: `"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { getStoredToken, isTokenExpired, refreshSession } from "@/lib/auth";
import type { AuthUser, AuthState } from "@/lib/auth";

const AuthContext = createContext<AuthState>({
  user: null,
  isAuthenticated: false,
  isLoading: true,
  error: null,
});

export function useAuthContext() {
  return useContext(AuthContext);
}

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<AuthState>({
    user: null,
    isAuthenticated: false,
    isLoading: true,
    error: null,
  });

  useEffect(() => {
    const token = getStoredToken();
    if (!token || isTokenExpired(token)) {
      setState({ user: null, isAuthenticated: false, isLoading: false, error: null });
      return;
    }
    refreshSession()
      .then((user: AuthUser | null) => {
        setState({ user, isAuthenticated: !!user, isLoading: false, error: null });
      })
      .catch((err: unknown) => {
        setState({
          user: null,
          isAuthenticated: false,
          isLoading: false,
          error: err instanceof Error ? err : new Error(String(err)),
        });
      });
  }, []);

  return <AuthContext.Provider value={state}>{children}</AuthContext.Provider>;
}
`,
  };
}

/** Generate placeholder .gitkeep files for directory structure */
export function generatePlaceholderFiles(): GeneratedFile[] {
  return [
    {
      path: 'hooks/.gitkeep',
      content: '',
    },
    {
      path: 'lib/.gitkeep',
      content: '',
    },
  ];
}

/** Generate .env.local template with Plumbus-specific variables */
export function generateEnvLocal(config: NextjsTemplateConfig): GeneratedFile {
  const baseUrl = config.apiBaseUrl ?? 'http://localhost:3000';
  return {
    path: '.env.local',
    content: `# Plumbus API
NEXT_PUBLIC_API_BASE_URL=${baseUrl}

# Auth
NEXT_PUBLIC_AUTH_ENABLED=${config.auth !== false ? 'true' : 'false'}
AUTH_SECRET=change-me-in-production

# Database (if using Next.js API routes with direct DB access)
# DATABASE_URL=postgresql://postgres:postgres@localhost:5432/plumbus
`,
  };
}

/** Generate a global error boundary component */
export function generateErrorBoundary(): GeneratedFile {
  return {
    path: 'app/error.tsx',
    content: `"use client";

import { useEffect } from "react";

export default function ErrorBoundary({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    console.error("Application error:", error);
  }, [error]);

  return (
    <main>
      <h2>Something went wrong</h2>
      <p>{error.message}</p>
      <button onClick={reset}>Try again</button>
    </main>
  );
}
`,
  };
}

/** Generate a global loading component */
export function generateLoadingComponent(): GeneratedFile {
  return {
    path: 'app/loading.tsx',
    content: `export default function Loading() {
  return (
    <main>
      <div role="status" aria-label="Loading">
        <p>Loading...</p>
      </div>
    </main>
  );
}
`,
  };
}

/** Generate Next.js proxy for auth token forwarding (proxy.ts replaces middleware.ts in Next.js 16+) */
export function generateProxy(config: NextjsTemplateConfig): GeneratedFile {
  const protectedPaths =
    config.auth !== false
      ? `
  // Protect routes that require authentication
  const protectedPaths = ["/dashboard", "/settings"];
  const isProtected = protectedPaths.some((p) => request.nextUrl.pathname.startsWith(p));

  if (isProtected) {
    const token = request.cookies.get("auth_token")?.value;
    if (!token) {
      return NextResponse.redirect(new URL("/login", request.url));
    }
  }
`
      : '';

  return {
    path: 'proxy.ts',
    content: `import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function proxy(request: NextRequest) {${protectedPaths}
  return NextResponse.next();
}

export const config = {
  matcher: [
    // Match all paths except static files and Next.js internals
    "/((?!_next/static|_next/image|favicon.ico).*)",
  ],
};
`,
  };
}

/** Generate a login page (only when auth is enabled) */
export function generateLoginPage(): GeneratedFile {
  return {
    path: 'app/login/page.tsx',
    content: `"use client";

import { useState } from "react";
import { login } from "@/lib/auth";

export default function LoginPage() {
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    const formData = new FormData(e.currentTarget);
    try {
      await login({
        email: formData.get("email") as string,
        password: formData.get("password") as string,
      });
      window.location.href = "/";
    } catch (err) {
      setError(err instanceof Error ? err.message : "Login failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main>
      <h1>Login</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="email">Email</label>
        <input id="email" name="email" type="email" required />
        <label htmlFor="password">Password</label>
        <input id="password" name="password" type="password" required />
        <button type="submit" disabled={loading}>
          {loading ? "Signing in..." : "Sign in"}
        </button>
      </form>
      {error && <p role="alert">{error}</p>}
      <p>Don&apos;t have an account? <a href="/signup">Sign up</a></p>
    </main>
  );
}
`,
  };
}

/** Generate a signup page (only when auth is enabled) */
export function generateSignupPage(): GeneratedFile {
  return {
    path: 'app/signup/page.tsx',
    content: `"use client";

import { useState } from "react";

export default function SignupPage() {
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    const formData = new FormData(e.currentTarget);
    try {
      const response = await fetch(
        (process.env["NEXT_PUBLIC_API_BASE_URL"] ?? "") + "/api/auth/signup",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            email: formData.get("email") as string,
            password: formData.get("password") as string,
            name: formData.get("name") as string,
          }),
        },
      );
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        throw new Error(body.message ?? "Signup failed");
      }
      window.location.href = "/login";
    } catch (err) {
      setError(err instanceof Error ? err.message : "Signup failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main>
      <h1>Sign Up</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="name">Name</label>
        <input id="name" name="name" type="text" required />
        <label htmlFor="email">Email</label>
        <input id="email" name="email" type="email" required />
        <label htmlFor="password">Password</label>
        <input id="password" name="password" type="password" required />
        <button type="submit" disabled={loading}>
          {loading ? "Creating account..." : "Sign up"}
        </button>
      </form>
      {error && <p role="alert">{error}</p>}
      <p>Already have an account? <a href="/login">Log in</a></p>
    </main>
  );
}
`,
  };
}

/** Generate the complete Next.js template file set */
export function generateNextjsTemplate(
  config: NextjsTemplateConfig,
  _capabilities?: CapabilityContract[],
): GeneratedFile[] {
  const files: GeneratedFile[] = [
    generatePackageJson(config),
    generateTsConfig(),
    generateGlobalsCss(),
    generatePostcssConfig(),
    generateLayout(config),
    generateHomePage(config),
    generateEnvLocal(config),
    generateErrorBoundary(),
    generateLoadingComponent(),
    generateProxy(config),
    ...generatePlaceholderFiles(),
  ];

  if (config.auth !== false) {
    files.push(generateAuthProvider());
    files.push(generateLoginPage());
    files.push(generateSignupPage());
  }

  return files;
}
