// ── Next.js Project Template Generator ──
// Generates a Next.js project scaffold with Plumbus auth integration,
// generated client imports, and example pages wired to capabilities.

import type { CapabilityContract } from "plumbus-core";

export interface NextjsTemplateConfig {
  /** Application name */
  appName: string;
  /** Whether to include auth wiring */
  auth?: boolean;
  /** Base URL for API calls */
  apiBaseUrl?: string;
}

// ── Helpers ──

function toPascalCase(str: string): string {
  return str.replace(/(^|[-_ ])(\w)/g, (_, _sep: string, c: string) => c.toUpperCase());
}

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, "$1-$2").replace(/[\s_]+/g, "-").toLowerCase();
}

// ── File Generators ──

export interface GeneratedFile {
  path: string;
  content: string;
}

/** Generate package.json for the Next.js project */
export function generatePackageJson(config: NextjsTemplateConfig): GeneratedFile {
  const name = toKebabCase(config.appName);
  const content = JSON.stringify({
    name,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
    },
    dependencies: {
      next: "^14.0.0",
      react: "^18.2.0",
      "react-dom": "^18.2.0",
    },
    devDependencies: {
      typescript: "^5.0.0",
      "@types/react": "^18.2.0",
      "@types/react-dom": "^18.2.0",
    },
  }, null, 2);

  return { path: "package.json", content };
}

/** Generate tsconfig.json */
export function generateTsConfig(): GeneratedFile {
  const content = JSON.stringify({
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      paths: { "@/*": ["./*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    exclude: ["node_modules"],
  }, null, 2);

  return { path: "tsconfig.json", content };
}

/** Generate the layout component */
export function generateLayout(config: NextjsTemplateConfig): GeneratedFile {
  const auth = config.auth !== false;

  const authImport = auth
    ? `import { AuthProvider } from "./components/AuthProvider";\n`
    : "";
  const authWrapOpen = auth ? "        <AuthProvider>\n" : "";
  const authWrapClose = auth ? "        </AuthProvider>\n" : "";

  return {
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next";
${authImport}
export const metadata: Metadata = {
  title: "${config.appName}",
  description: "Generated by @plumbus/ui",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
${authWrapOpen}          {children}
${authWrapClose}      </body>
    </html>
  );
}
`,
  };
}

/** Generate the home page */
export function generateHomePage(config: NextjsTemplateConfig): GeneratedFile {
  return {
    path: "app/page.tsx",
    content: `export default function Home() {
  return (
    <main>
      <h1>${config.appName}</h1>
      <p>Welcome to your Plumbus application.</p>
    </main>
  );
}
`,
  };
}

/** Generate example page for a capability */
export function generateCapabilityPage(cap: CapabilityContract): GeneratedFile {
  const pascal = toPascalCase(cap.name);
  const slug = toKebabCase(cap.name);

  if (cap.kind === "query") {
    return {
      path: `app/${slug}/page.tsx`,
      content: `"use client";

import { use${pascal} } from "@/generated/hooks";

export default function ${pascal}Page() {
  const { data, loading, error } = use${pascal}({});

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <main>
      <h1>${cap.name}</h1>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </main>
  );
}
`,
    };
  }

  return {
    path: `app/${slug}/page.tsx`,
    content: `"use client";

import { use${pascal} } from "@/generated/hooks";

export default function ${pascal}Page() {
  const { mutate, data, loading, error, reset } = use${pascal}();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const input = Object.fromEntries(formData.entries());
    await mutate(input as Record<string, unknown>);
  };

  return (
    <main>
      <h1>${cap.name}</h1>
      <form onSubmit={handleSubmit}>
        <button type="submit" disabled={loading}>
          {loading ? "Processing..." : "Submit"}
        </button>
      </form>
      {error && <p>Error: {error.message}</p>}
      {data && (
        <div>
          <pre>{JSON.stringify(data, null, 2)}</pre>
          <button onClick={reset}>Reset</button>
        </div>
      )}
    </main>
  );
}
`,
  };
}

/** Generate AuthProvider component */
export function generateAuthProvider(): GeneratedFile {
  return {
    path: "components/AuthProvider.tsx",
    content: `"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { getStoredToken, isTokenExpired, refreshSession } from "@/generated/auth";
import type { AuthUser, AuthState } from "@/generated/auth";

const AuthContext = createContext<AuthState>({
  user: null,
  isAuthenticated: false,
  isLoading: true,
  error: null,
});

export function useAuthContext() {
  return useContext(AuthContext);
}

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<AuthState>({
    user: null,
    isAuthenticated: false,
    isLoading: true,
    error: null,
  });

  useEffect(() => {
    const token = getStoredToken();
    if (!token || isTokenExpired(token)) {
      setState({ user: null, isAuthenticated: false, isLoading: false, error: null });
      return;
    }
    refreshSession()
      .then((user: AuthUser | null) => {
        setState({ user, isAuthenticated: !!user, isLoading: false, error: null });
      })
      .catch((err: unknown) => {
        setState({
          user: null,
          isAuthenticated: false,
          isLoading: false,
          error: err instanceof Error ? err : new Error(String(err)),
        });
      });
  }, []);

  return <AuthContext.Provider value={state}>{children}</AuthContext.Provider>;
}
`,
  };
}

/** Generate the "generated" directory placeholder */
export function generatePlaceholderFiles(): GeneratedFile[] {
  return [
    {
      path: "generated/.gitkeep",
      content: "",
    },
    {
      path: "hooks/.gitkeep",
      content: "",
    },
  ];
}

/** Generate .env.local template with Plumbus-specific variables */
export function generateEnvLocal(config: NextjsTemplateConfig): GeneratedFile {
  const baseUrl = config.apiBaseUrl ?? "http://localhost:3000";
  return {
    path: ".env.local",
    content: `# Plumbus API
NEXT_PUBLIC_API_BASE_URL=${baseUrl}

# Auth
NEXT_PUBLIC_AUTH_ENABLED=${config.auth !== false ? "true" : "false"}
AUTH_SECRET=change-me-in-production

# Database (if using Next.js API routes with direct DB access)
# DATABASE_URL=postgresql://postgres:postgres@localhost:5432/plumbus
`,
  };
}

/** Generate a global error boundary component */
export function generateErrorBoundary(): GeneratedFile {
  return {
    path: "app/error.tsx",
    content: `"use client";

import { useEffect } from "react";

export default function ErrorBoundary({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    console.error("Application error:", error);
  }, [error]);

  return (
    <main>
      <h2>Something went wrong</h2>
      <p>{error.message}</p>
      <button onClick={reset}>Try again</button>
    </main>
  );
}
`,
  };
}

/** Generate a global loading component */
export function generateLoadingComponent(): GeneratedFile {
  return {
    path: "app/loading.tsx",
    content: `export default function Loading() {
  return (
    <main>
      <div role="status" aria-label="Loading">
        <p>Loading...</p>
      </div>
    </main>
  );
}
`,
  };
}

/** Generate Next.js middleware for auth token forwarding */
export function generateMiddleware(config: NextjsTemplateConfig): GeneratedFile {
  const protectedPaths = config.auth !== false
    ? `
  // Protect routes that require authentication
  const protectedPaths = ["/dashboard", "/settings", "/api/protected"];
  const isProtected = protectedPaths.some((p) => request.nextUrl.pathname.startsWith(p));

  if (isProtected) {
    const token = request.cookies.get("auth_token")?.value;
    if (!token) {
      return NextResponse.redirect(new URL("/login", request.url));
    }
  }
`
    : "";

  return {
    path: "middleware.ts",
    content: `import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(request: NextRequest) {${protectedPaths}
  return NextResponse.next();
}

export const config = {
  matcher: [
    // Match all paths except static files and Next.js internals
    "/((?!_next/static|_next/image|favicon.ico).*)",
  ],
};
`,
  };
}

/** Generate API route helper for proxying to the Plumbus backend */
export function generateApiRouteHelper(config: NextjsTemplateConfig): GeneratedFile {
  const baseUrl = config.apiBaseUrl ?? "http://localhost:3000";
  return {
    path: "app/api/plumbus/[...path]/route.ts",
    content: `import { NextRequest, NextResponse } from "next/server";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "${baseUrl}";

/**
 * Proxy handler that forwards requests to the Plumbus API server.
 * Forwards auth headers and returns the upstream response.
 */
async function handler(request: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const { path } = await params;
  const target = new URL(path.join("/"), API_BASE);

  // Forward query parameters
  request.nextUrl.searchParams.forEach((value, key) => {
    target.searchParams.set(key, value);
  });

  const headers = new Headers(request.headers);
  headers.delete("host");

  const resp = await fetch(target.toString(), {
    method: request.method,
    headers,
    body: request.method !== "GET" && request.method !== "HEAD" ? await request.text() : undefined,
  });

  const body = await resp.text();
  return new NextResponse(body, {
    status: resp.status,
    headers: { "Content-Type": resp.headers.get("Content-Type") ?? "application/json" },
  });
}

export const GET = handler;
export const POST = handler;
export const PUT = handler;
export const PATCH = handler;
export const DELETE = handler;
`,
  };
}

/** Generate the complete Next.js template file set */
export function generateNextjsTemplate(
  config: NextjsTemplateConfig,
  capabilities?: CapabilityContract[],
): GeneratedFile[] {
  const files: GeneratedFile[] = [
    generatePackageJson(config),
    generateTsConfig(),
    generateLayout(config),
    generateHomePage(config),
    generateEnvLocal(config),
    generateErrorBoundary(),
    generateLoadingComponent(),
    generateMiddleware(config),
    generateApiRouteHelper(config),
    ...generatePlaceholderFiles(),
  ];

  if (config.auth !== false) {
    files.push(generateAuthProvider());
  }

  if (capabilities) {
    for (const cap of capabilities) {
      files.push(generateCapabilityPage(cap));
    }
  }

  return files;
}
