// ── Translation Module Generator ──
// Generates i18n modules from discovered TranslationDefinition contracts.
// Output: merged message catalog, config, provider component, and hook re-exports.

import type { TranslationDefinition } from '@plumbus/core';

export interface GeneratedTranslationFile {
  path: string;
  content: string;
}

/** Well-known RTL locales */
const RTL_LOCALES = new Set(['ar', 'he', 'fa', 'ur', 'ps', 'sd', 'yi']);

/**
 * Expand flat dotted keys into nested objects.
 * e.g. {"nav.overview": "Overview"} → {nav: {overview: "Overview"}}
 * next-intl resolves dots as nested paths, so keys must be nested.
 */
function unflattenMessages(flat: Record<string, string>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split('.');
    let current: Record<string, unknown> = result;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i] ?? '';
      if (!(part in current) || typeof current[part] !== 'object') {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }
    const last = parts[parts.length - 1] ?? key;
    current[last] = value;
  }
  return result;
}

/**
 * Generate the merged message catalog module.
 * Exports: `messages` — Record<locale, Record<namespace, nested messages>>
 * Dotted keys are expanded into nested objects for next-intl compatibility.
 */
function generateMessagesCatalog(definitions: TranslationDefinition[]): string {
  const allLocales = [...new Set(definitions.flatMap((d) => d.locales))];
  const catalog: Record<string, Record<string, unknown>> = {};

  for (const locale of allLocales) {
    catalog[locale] = {};
    for (const def of definitions) {
      const msgs = def.messages[locale];
      if (msgs) {
        catalog[locale][def.name] = unflattenMessages(msgs);
      }
    }
  }

  return `// Auto-generated by plumbus ui generate — do not edit
export const messages = ${JSON.stringify(catalog, null, 2)} as const;
`;
}

/**
 * Generate the i18n config module.
 * Exports: locales, defaultLocale, rtlLocales
 */
function generateConfig(definitions: TranslationDefinition[]): string {
  const allLocales = [...new Set(definitions.flatMap((d) => d.locales))];
  const defaultLocale = definitions[0]?.defaultLocale ?? 'en';
  const rtlLocales = allLocales.filter((l) => RTL_LOCALES.has(l));

  return `// Auto-generated by plumbus ui generate — do not edit
export const locales = ${JSON.stringify(allLocales)} as const;
export const defaultLocale = ${JSON.stringify(defaultLocale)};
export const rtlLocales = ${JSON.stringify(rtlLocales)} as const;
export type Locale = (typeof locales)[number];
`;
}

/**
 * Generate the next-intl request config (for server components).
 */
function generateRequestConfig(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
import { getRequestConfig } from "@plumbus/ui/next-intl-server";
import { messages } from "./messages";
import { defaultLocale } from "./config";
import type { Locale } from "./config";

export default getRequestConfig(async ({ requestLocale }) => {
  const locale = ((await requestLocale) ?? defaultLocale) as Locale;
  return {
    locale,
    messages: messages[locale] ?? messages[defaultLocale as Locale],
  };
});
`;
}

/**
 * Generate the TranslationProvider client component.
 * Wraps NextIntlClientProvider and manages locale state via localStorage.
 */
function generateProvider(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
"use client";

import { NextIntlClientProvider } from "@plumbus/ui/next-intl";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { messages } from "./messages";
import { defaultLocale, rtlLocales } from "./config";
import type { Locale } from "./config";

const LOCALE_STORAGE_KEY = "plumbus-ui-locale";

interface LocaleContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
}

const LocaleContext = createContext<LocaleContextValue>({
  locale: defaultLocale as Locale,
  setLocale: () => {},
});

export function useLocale(): LocaleContextValue {
  return useContext(LocaleContext);
}

export function TranslationProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(defaultLocale as Locale);

  useEffect(() => {
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
    if (stored && stored in messages) {
      setLocaleState(stored as Locale);
    }
  }, []);

  useEffect(() => {
    const isRtl = rtlLocales.includes(locale as (typeof rtlLocales)[number]);
    document.documentElement.lang = locale;
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
  }, [locale]);

  const setLocale = useCallback((newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem(LOCALE_STORAGE_KEY, newLocale);
  }, []);

  const contextValue = useMemo(() => ({ locale, setLocale }), [locale, setLocale]);

  return (
    <LocaleContext.Provider value={contextValue}>
      <NextIntlClientProvider locale={locale} messages={messages[locale]}>
        {children}
      </NextIntlClientProvider>
    </LocaleContext.Provider>
  );
}
`;
}

/**
 * Generate the useTranslation hook re-export module.
 */
function generateUseTranslation(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
export { useTranslations } from "@plumbus/ui/next-intl";
export { useLocale } from "./provider";
export type { Locale } from "./config";
export { locales, defaultLocale, rtlLocales } from "./config";
`;
}

/**
 * Generate all i18n module files from discovered translation definitions.
 */
export function generateTranslationModule(
  definitions: TranslationDefinition[],
): GeneratedTranslationFile[] {
  if (definitions.length === 0) return [];

  return [
    { path: 'i18n/messages.ts', content: generateMessagesCatalog(definitions) },
    { path: 'i18n/config.ts', content: generateConfig(definitions) },
    { path: 'i18n/request.ts', content: generateRequestConfig() },
    { path: 'i18n/provider.tsx', content: generateProvider() },
    { path: 'i18n/index.ts', content: generateUseTranslation() },
  ];
}
