// ── Translation Module Generator ──
// Generates i18n modules from discovered TranslationDefinition contracts.
// Output: merged message catalog, config, provider component, and hook re-exports.

import type { TranslationDefinition } from '@plumbus/core';

export interface GeneratedTranslationFile {
  path: string;
  content: string;
}

/** Well-known RTL locales */
const RTL_LOCALES = new Set(['ar', 'he', 'fa', 'ur', 'ps', 'sd', 'yi']);

/**
 * Expand flat dotted keys into nested objects.
 * e.g. {"nav.overview": "Overview"} → {nav: {overview: "Overview"}}
 * next-intl resolves dots as nested paths, so keys must be nested.
 */
function unflattenMessages(flat: Record<string, string>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split('.');
    let current: Record<string, unknown> = result;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i] ?? '';
      if (!(part in current) || typeof current[part] !== 'object') {
        current[part] = {};
      }
      current = current[part] as Record<string, unknown>;
    }
    const last = parts[parts.length - 1] ?? key;
    current[last] = value;
  }
  return result;
}

function buildMessageCatalog(
  definitions: TranslationDefinition[],
): Record<string, Record<string, unknown>> {
  const allLocales = [...new Set(definitions.flatMap((d) => d.locales))];
  const catalog: Record<string, Record<string, unknown>> = {};

  for (const locale of allLocales) {
    catalog[locale] = {};
    for (const def of definitions) {
      const msgs = def.messages[locale];
      if (msgs) {
        catalog[locale][def.name] = unflattenMessages(msgs);
      }
    }
  }

  return catalog;
}

/**
 * Generate the merged message catalog module.
 * Exports: `messages` — Record<locale, Record<namespace, nested messages>>
 * Dotted keys are expanded into nested objects for next-intl compatibility.
 */
function generateMessagesCatalog(definitions: TranslationDefinition[]): string {
  const catalog = buildMessageCatalog(definitions);

  return `// Auto-generated by plumbus ui generate — do not edit
export const messages = ${JSON.stringify(catalog, null, 2)} as const;
`;
}

function generateSplitLocaleBundle(catalog: Record<string, unknown>): string {
  return `// Auto-generated by plumbus ui generate — do not edit
export const localeMessages = ${JSON.stringify(catalog, null, 2)} as const;
`;
}

function generateSplitMessagesAggregator(locales: string[]): string {
  const imports = locales
    .map(
      (locale) =>
        `import { localeMessages as ${locale.replace(/[^a-zA-Z0-9_]/g, '_')} } from "./locales/${locale}";`,
    )
    .join('\n');
  const entries = locales
    .map((locale) => {
      const id = locale.replace(/[^a-zA-Z0-9_]/g, '_');
      return `  ${JSON.stringify(locale)}: ${id},`;
    })
    .join('\n');

  return `// Auto-generated by plumbus ui generate — do not edit
${imports}

export const messages = {
${entries}
} as const;
`;
}

/**
 * Generate the i18n config module.
 * Exports: locales, defaultLocale, rtlLocales
 */
function generateConfig(definitions: TranslationDefinition[]): string {
  const allLocales = [...new Set(definitions.flatMap((d) => d.locales))];
  const defaultLocale = definitions[0]?.defaultLocale ?? 'en';
  const rtlLocales = allLocales.filter((l) => RTL_LOCALES.has(l));

  return `// Auto-generated by plumbus ui generate — do not edit
export const locales = ${JSON.stringify(allLocales)} as const;
export const defaultLocale = ${JSON.stringify(defaultLocale)};
export const rtlLocales = ${JSON.stringify(rtlLocales)} as const;
export type Locale = (typeof locales)[number];
`;
}

/**
 * Generate the next-intl request config (for server components).
 */
function generateRequestConfig(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
import { getRequestConfig } from "@plumbus/ui/next-intl-server";
import { cookies } from "next/headers";
import { messages } from "./messages";
import { defaultLocale, locales } from "./config";
import type { Locale } from "./config";

const LOCALE_COOKIE_KEY = "plumbus-ui-locale";

export default getRequestConfig(async ({ requestLocale }) => {
  const requested = await requestLocale;
  const cookieLocale = (await cookies()).get(LOCALE_COOKIE_KEY)?.value;
  const candidate = requested ?? cookieLocale ?? defaultLocale;
  const locale = (locales.includes(candidate as Locale) ? candidate : defaultLocale) as Locale;
  return {
    locale,
    messages: messages[locale] ?? messages[defaultLocale as Locale],
    timeZone: "UTC",
  };
});
`;
}

/**
 * Generate the TranslationProvider client component.
 * Wraps NextIntlClientProvider and manages locale state via localStorage.
 */
function generateProvider(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
"use client";

import { NextIntlClientProvider } from "@plumbus/ui/next-intl";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { messages } from "./messages";
import { defaultLocale, rtlLocales } from "./config";
import type { Locale } from "./config";

const LOCALE_STORAGE_KEY = "plumbus-ui-locale";
const LOCALE_COOKIE_KEY = "plumbus-ui-locale";
const LOCALE_COOKIE_MAX_AGE = 60 * 60 * 24 * 365;

function persistLocale(locale: Locale) {
  try {
    localStorage.setItem(LOCALE_STORAGE_KEY, locale);
  } catch {}
  document.cookie = \`\${LOCALE_COOKIE_KEY}=\${locale}; path=/; max-age=\${LOCALE_COOKIE_MAX_AGE}; samesite=lax\`;
}

interface LocaleContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
}

const LocaleContext = createContext<LocaleContextValue>({
  locale: defaultLocale as Locale,
  setLocale: () => {},
});

export function useLocale(): LocaleContextValue {
  return useContext(LocaleContext);
}

export function TranslationProvider({
  children,
  initialLocale,
}: {
  children: ReactNode;
  initialLocale?: Locale;
}) {
  const [locale, setLocaleState] = useState<Locale>(initialLocale ?? (defaultLocale as Locale));

  useEffect(() => {
    if (initialLocale) return;
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
    if (stored && stored in messages) {
      setLocaleState(stored as Locale);
    }
  }, [initialLocale]);

  useEffect(() => {
    const isRtl = rtlLocales.includes(locale as (typeof rtlLocales)[number]);
    document.documentElement.lang = locale;
    document.documentElement.dir = isRtl ? "rtl" : "ltr";
  }, [locale]);

  const setLocale = useCallback((newLocale: Locale) => {
    setLocaleState(newLocale);
    persistLocale(newLocale);
  }, []);

  const contextValue = useMemo(() => ({ locale, setLocale }), [locale, setLocale]);

  return (
    <LocaleContext.Provider value={contextValue}>
      <NextIntlClientProvider locale={locale} messages={messages[locale]} timeZone="UTC">
        {children}
      </NextIntlClientProvider>
    </LocaleContext.Provider>
  );
}
`;
}

/**
 * Generate the useTranslation hook re-export module.
 */
function generateUseTranslation(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
export { useTranslations } from "@plumbus/ui/next-intl";
export { useLocale } from "./provider";
export type { Locale } from "./config";
export { locales, defaultLocale, rtlLocales } from "./config";
`;
}

export interface TranslationGeneratorOptions {
  /** Emit per-locale bundles under i18n/locales/ (default: single i18n/messages.ts). */
  splitLocaleBundles?: boolean;
}

/**
 * Generate all i18n module files from discovered translation definitions.
 */
export function generateTranslationModule(
  definitions: TranslationDefinition[],
  options: TranslationGeneratorOptions = {},
): GeneratedTranslationFile[] {
  if (definitions.length === 0) return [];

  const catalog = buildMessageCatalog(definitions);
  const locales = Object.keys(catalog);

  const files: GeneratedTranslationFile[] = [];

  if (options.splitLocaleBundles) {
    for (const locale of locales) {
      files.push({
        path: `i18n/locales/${locale}.ts`,
        content: generateSplitLocaleBundle(catalog[locale] ?? {}),
      });
    }
    files.push({
      path: 'i18n/messages.ts',
      content: generateSplitMessagesAggregator(locales),
    });
  } else {
    files.push({
      path: 'i18n/messages.ts',
      content: generateMessagesCatalog(definitions),
    });
  }

  files.push(
    { path: 'i18n/config.ts', content: generateConfig(definitions) },
    { path: 'i18n/request.ts', content: generateRequestConfig() },
    { path: 'i18n/provider.tsx', content: generateProvider() },
    { path: 'i18n/index.ts', content: generateUseTranslation() },
  );

  return files;
}
