// ── Translation Module Generator ──
// Generates i18n modules from discovered TranslationDefinition contracts.
// Output: merged message catalog, config, provider, typed keys, TranslatedText brand, AppConfig augmentation.

import type { TranslationDefinition } from '@plumbus/core';

export interface GeneratedTranslationFile {
  path: string;
  content: string;
}

/** Well-known RTL locales */
const RTL_LOCALES = new Set(['ar', 'he', 'fa', 'ur', 'ps', 'sd', 'yi']);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Expand flat dotted keys into nested objects.
 * e.g. {"nav.overview": "Overview"} → {nav: {overview: "Overview"}}
 * next-intl resolves dots as nested paths, so keys must be nested.
 */
function unflattenMessages(flat: Record<string, string>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split('.');
    let current: Record<string, unknown> = result;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i] ?? '';
      const existing = current[part];
      if (isPlainObject(existing)) {
        current = existing;
      } else {
        const next: Record<string, unknown> = {};
        current[part] = next;
        current = next;
      }
    }
    const last = parts[parts.length - 1] ?? key;
    current[last] = value;
  }
  return result;
}

function buildMessageCatalog(
  definitions: TranslationDefinition[],
): Record<string, Record<string, unknown>> {
  const allLocales = [...new Set(definitions.flatMap((d) => d.locales))];
  const catalog: Record<string, Record<string, unknown>> = {};

  for (const locale of allLocales) {
    catalog[locale] = {};
    for (const def of definitions) {
      const msgs = def.messages[locale];
      if (msgs) {
        catalog[locale][def.name] = unflattenMessages(msgs);
      }
    }
  }

  return catalog;
}

/**
 * Generate the merged message catalog module.
 * Exports: `messages` — Record<locale, Record<namespace, nested messages>>
 * Dotted keys are expanded into nested objects for next-intl compatibility.
 */
function generateMessagesCatalog(definitions: TranslationDefinition[]): string {
  const catalog = buildMessageCatalog(definitions);
  const defaultLocale = resolveSharedDefaultLocale(definitions);

  return `// Auto-generated by plumbus ui generate — do not edit
const rawMessages = ${JSON.stringify(catalog, null, 2)} as const;

// Each locale is typed as the default locale's shape, so messages[locale] is a single
// consistent type assignable to Messages (which is derived from the default locale).
// Plain "as const" makes each locale a divergent literal type whose union is not
// assignable to next-intl's provider messages prop.
export const messages = rawMessages as unknown as {
  [L in keyof typeof rawMessages]: (typeof rawMessages)[${JSON.stringify(defaultLocale)}];
};
`;
}

function generateSplitLocaleBundle(catalog: Record<string, unknown>): string {
  return `// Auto-generated by plumbus ui generate — do not edit
export const localeMessages = ${JSON.stringify(catalog, null, 2)} as const;
`;
}

function generateSplitMessagesAggregator(locales: string[], defaultLocale: string): string {
  const imports = locales
    .map(
      (locale) =>
        `import { localeMessages as ${locale.replace(/[^a-zA-Z0-9_]/g, '_')} } from "./locales/${locale}";`,
    )
    .join('\n');
  const entries = locales
    .map((locale) => {
      const id = locale.replace(/[^a-zA-Z0-9_]/g, '_');
      return `  ${JSON.stringify(locale)}: ${id},`;
    })
    .join('\n');

  return `// Auto-generated by plumbus ui generate — do not edit
${imports}

const rawMessages = {
${entries}
} as const;

// Each locale is typed as the default locale's shape, so messages[locale] is a single
// consistent type assignable to Messages (which is derived from the default locale).
export const messages = rawMessages as unknown as {
  [L in keyof typeof rawMessages]: (typeof rawMessages)[${JSON.stringify(defaultLocale)}];
};
`;
}

/**
 * Generate the i18n config module.
 * Exports: locales, defaultLocale, rtlLocales, localeSchema, isLocale, localeDir.
 */
function generateConfig(definitions: TranslationDefinition[]): string {
  const allLocales = [...new Set(definitions.flatMap((d) => d.locales))];
  const defaultLocale = resolveSharedDefaultLocale(definitions);
  const rtlLocales = allLocales.filter((l) => RTL_LOCALES.has(l));

  const rtlBlock =
    rtlLocales.length > 0
      ? `
export const rtlLocaleSchema = z.enum(rtlLocales);

export function localeDir(locale: Locale): "rtl" | "ltr" {
  return rtlLocaleSchema.safeParse(locale).success ? "rtl" : "ltr";
}
`
      : `
export function localeDir(_locale: Locale): "rtl" | "ltr" {
  return "ltr";
}
`;

  return `// Auto-generated by plumbus ui generate — do not edit
import { z } from "@plumbus/core/zod";

export const locales = ${JSON.stringify(allLocales)} as const;
export type Locale = (typeof locales)[number];
// Literal type (not \`Locale\`) so Messages indexes one catalog, not a locale union.
export const defaultLocale = ${JSON.stringify(defaultLocale)} as const satisfies Locale;
export const rtlLocales = ${JSON.stringify(rtlLocales)} as const satisfies ReadonlyArray<Locale>;

export const localeSchema = z.enum(locales);

export function isLocale(value: string): value is Locale {
  return localeSchema.safeParse(value).success;
}
${rtlBlock}`;
}

function generateKeysModule(): string {
  // Use `typeof import(...)` so Messages stays correct even if a formatter
  // rewrites value imports to `import type` (which breaks `typeof messages`).
  return `// Auto-generated by plumbus ui generate — do not edit
import type { ICUArgs } from "@plumbus/ui/next-intl";
import type { Locale } from "./config";

export type { Locale };

/** Nested message catalog for the default locale (next-intl Messages shape). */
export type Messages =
  (typeof import("./messages").messages)[typeof import("./config").defaultLocale];

/** Namespace names present in the catalog. */
export type Namespace = keyof Messages & string;

type NestedKeyOf<T> = T extends string
  ? never
  : {
      [K in keyof T & string]: T[K] extends string
        ? K
        : T[K] extends Record<string, unknown>
          ? \`\${K}.\${NestedKeyOf<T[K]>}\`
          : K;
    }[keyof T & string];

type NestedValueOf<T, Path extends string> = Path extends \`\${infer Head}.\${infer Rest}\`
  ? Head extends keyof T
    ? NestedValueOf<T[Head], Rest>
    : never
  : Path extends keyof T
    ? T[Path]
    : never;

/** Message key within a namespace (\`nav.home\`, not \`common.nav.home\`). */
export type MessageKeyOf<N extends Namespace> = NestedKeyOf<Messages[N]>;

/**
 * ICU argument object for a message key (names + types from the message string).
 * Plain strings → \`{}\`; \`{name}\` → \`{ name: string }\`; plural/select → number fields; etc.
 * \`[K]\` keeps this from distributing over key unions (which breaks required-args checking).
 */
export type MessageArgsOf<N extends Namespace, K extends MessageKeyOf<N>> = [K] extends [
  infer Key extends MessageKeyOf<N>,
]
  ? NestedValueOf<Messages[N], Key> extends infer Value
    ? Value extends string
      ? ICUArgs<
          Value,
          {
            ICUArgument: string;
            ICUNumberArgument: number | bigint;
            ICUDateArgument: Date;
          }
        >
      : never
    : never
  : never;

/** Fully-qualified key: \`namespace.path.to.key\` (for props / harvest maps). */
export type I18nKey = {
  [N in Namespace]: \`\${N}.\${MessageKeyOf<N>}\`;
}[Namespace];
`;
}

function generateNextIntlAugmentation(): string {
  // Official next-intl AppConfig (`global.ts`). Needs a resolvable `next-intl`
  // at the app root (peer of @plumbus/ui). Generated `useTranslations` in
  // i18n/index.ts is typed via MessageKeyOf and does not depend on this.
  return `// Auto-generated by plumbus ui generate — do not edit
import "next-intl";
import { messages } from "./messages";
import { defaultLocale, locales } from "./config";

declare module "next-intl" {
  interface AppConfig {
    Locale: (typeof locales)[number];
    Messages: (typeof messages)[typeof defaultLocale];
  }
}
`;
}

/**
 * Generate the next-intl request config (for server components).
 *
 * By default the locale is resolved from `requestLocale` only, which keeps the
 * config statically renderable. When `serverLocaleCookie` is enabled, it also reads
 * the `plumbus-ui-locale` cookie as a fallback so Server Components render the stored
 * locale on first paint — at the cost of opting routes into dynamic rendering
 * (`cookies()` is a Next.js Dynamic API, unsupported under `output: 'export'`).
 */
function generateRequestConfig(serverLocaleCookie = false): string {
  if (!serverLocaleCookie) {
    return `// Auto-generated by plumbus ui generate — do not edit
import "./global";
import { getRequestConfig } from "@plumbus/ui/next-intl-server";
import {
  getMissingMessageFallback,
  onTranslationError,
} from "@plumbus/ui/next-intl";
import { messages } from "./messages";
import { defaultLocale, isLocale } from "./config";
import type { Locale } from "./config";

export default getRequestConfig(async ({ requestLocale }) => {
  const requested = await requestLocale;
  const locale: Locale = requested !== undefined && isLocale(requested) ? requested : defaultLocale;
  return {
    locale,
    messages: messages[locale],
    timeZone: "UTC",
    onError: onTranslationError,
    getMessageFallback: getMissingMessageFallback,
  };
});
`;
  }

  return `// Auto-generated by plumbus ui generate — do not edit
import "./global";
import { getRequestConfig } from "@plumbus/ui/next-intl-server";
import {
  getMissingMessageFallback,
  onTranslationError,
} from "@plumbus/ui/next-intl";
import { cookies } from "next/headers";
import { messages } from "./messages";
import { defaultLocale, isLocale } from "./config";
import type { Locale } from "./config";

const LOCALE_COOKIE_KEY = "plumbus-ui-locale";

export default getRequestConfig(async ({ requestLocale }) => {
  const requested = await requestLocale;
  // Only read the (dynamic) cookie store when the URL didn't resolve a locale,
  // so URL-locale routes stay statically renderable.
  const fromCookie = requested === undefined || requested === null
    ? (await cookies()).get(LOCALE_COOKIE_KEY)?.value
    : undefined;
  const candidate = requested ?? fromCookie ?? defaultLocale;
  const locale: Locale = isLocale(candidate) ? candidate : defaultLocale;
  return {
    locale,
    messages: messages[locale],
    timeZone: "UTC",
    onError: onTranslationError,
    getMessageFallback: getMissingMessageFallback,
  };
});
`;
}

/**
 * Generate the TranslationProvider client component.
 * Wraps NextIntlClientProvider and manages locale state via localStorage.
 */
function generateProvider(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
"use client";

import {
  NextIntlClientProvider,
  getMissingMessageFallback,
  onTranslationError,
} from "@plumbus/ui/next-intl";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { messages } from "./messages";
import { defaultLocale, isLocale, localeDir } from "./config";
import type { Locale } from "./config";

const LOCALE_STORAGE_KEY = "plumbus-ui-locale";
const LOCALE_COOKIE_KEY = "plumbus-ui-locale";
const LOCALE_COOKIE_MAX_AGE = 60 * 60 * 24 * 365;

function persistLocale(locale: Locale) {
  try {
    localStorage.setItem(LOCALE_STORAGE_KEY, locale);
  } catch {
    // Ignore quota / private-mode failures — in-memory locale still applies.
  }
  const secure = location.protocol === "https:" ? "; secure" : "";
  document.cookie = \`\${LOCALE_COOKIE_KEY}=\${locale}; path=/; max-age=\${LOCALE_COOKIE_MAX_AGE}; samesite=lax\${secure}\`;
}

interface LocaleContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
}

const LocaleContext = createContext<LocaleContextValue>({
  locale: defaultLocale,
  setLocale: () => {},
});

export function useLocale(): LocaleContextValue {
  return useContext(LocaleContext);
}

export function TranslationProvider({
  children,
  initialLocale,
}: {
  children: ReactNode;
  initialLocale?: Locale;
}) {
  const [locale, setLocaleState] = useState<Locale>(initialLocale ?? defaultLocale);

  useEffect(() => {
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
    if (stored !== null && isLocale(stored) && Object.hasOwn(messages, stored)) {
      setLocaleState(stored);
      if (initialLocale !== undefined && stored !== initialLocale) {
        // Server rendered initialLocale but the client has a newer stored preference
        // (e.g. the cookie was cleared or expired) — adopt it and re-sync the cookie.
        persistLocale(stored);
      }
    }
  }, [initialLocale]);

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = localeDir(locale);
  }, [locale]);

  const setLocale = useCallback((newLocale: Locale) => {
    setLocaleState(newLocale);
    persistLocale(newLocale);
  }, []);

  const contextValue = useMemo(() => ({ locale, setLocale }), [locale, setLocale]);

  return (
    <LocaleContext.Provider value={contextValue}>
      <NextIntlClientProvider
        locale={locale}
        messages={messages[locale]}
        timeZone="UTC"
        onError={onTranslationError}
        getMessageFallback={getMissingMessageFallback}
      >
        {children}
      </NextIntlClientProvider>
    </LocaleContext.Provider>
  );
}
`;
}

/**
 * Emit the opaque `TranslatedText` brand used by generated `t` / `markup`.
 * Branding lives on resolver returns — not on catalog `Messages` leaves.
 */
function generateTranslatedTextModule(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
declare const translatedTextBrand: unique symbol;

/** Branded resolved UI copy from \`t()\` / \`markup\`. Do not cast values to this type. */
export type TranslatedText = string & {
  readonly [translatedTextBrand]: "TranslatedText";
};

/**
 * @internal Emit-only — used by generated \`useTranslations\`. Not a public escape hatch;
 * consumers must not import this to forge display strings.
 */
export function brandTranslatedText(value: string): TranslatedText {
  return value as TranslatedText;
}
`;
}

/**
 * Generate the useTranslation hook re-export module.
 *
 * `useTranslations` is a thin wrapper that binds keys to generated `Messages`.
 * That stays correct even when AppConfig augmentation cannot see the same
 * physical `next-intl` copy as `@plumbus/ui/next-intl` (nested installs).
 *
 * `t` / `markup` return branded `TranslatedText` so apps can gate JSX/attrs on
 * provenance; `brandTranslatedText` stays emit-internal (not re-exported here).
 */
function generateUseTranslation(): string {
  return `// Auto-generated by plumbus ui generate — do not edit
"use client";

import {
  useCatalogTranslations,
  useFormatter,
} from "@plumbus/ui/next-intl";
import type { ReactNode } from "react";
import type { MessageArgsOf, MessageKeyOf, Namespace } from "./keys";
import { brandTranslatedText } from "./translated-text";
import type { TranslatedText } from "./translated-text";

export { useFormatter };
export { useLocale } from "./provider";
export type { Locale } from "./config";
export type {
  I18nKey,
  MessageArgsOf,
  MessageKeyOf,
  Messages,
  Namespace,
} from "./keys";
export type { TranslatedText } from "./translated-text";
export { locales, defaultLocale, rtlLocales, localeSchema, isLocale, localeDir } from "./config";

/**
 * Rest-args for one concrete Args object (non-distributive over unions).
 * No ICU fields → no values arg; required fields → \`[values]\`; all-optional → \`[values?]\`.
 */
type TranslateValuesArgs<Args> = [Args] extends [infer A]
  ? keyof A extends never
    ? []
    : Partial<A> extends A
      ? [values?: A]
      : [values: A]
  : never;

/** Namespace-bound translator — exported so call sites keep per-key \`K\` inference. */
export type TranslationsFor<N extends Namespace> = {
  <K extends MessageKeyOf<N>>(
    key: K,
    ...args: TranslateValuesArgs<MessageArgsOf<N, K>>
  ): TranslatedText;
  rich: <K extends MessageKeyOf<N>>(
    key: K,
    ...args: TranslateValuesArgs<MessageArgsOf<N, K>>
  ) => ReactNode;
  markup: <K extends MessageKeyOf<N>>(
    key: K,
    ...args: TranslateValuesArgs<MessageArgsOf<N, K>>
  ) => TranslatedText;
  raw: <K extends MessageKeyOf<N>>(key: K) => unknown;
  has: <K extends MessageKeyOf<N>>(key: K) => boolean;
};

/**
 * Typed \`useTranslations\` — namespaces, keys, and ICU params come from the catalog.
 * Prefer this (or \`i18n\`) over importing \`useTranslations\` from \`@plumbus/ui/next-intl\` directly.
 *
 * The explicit \`TranslationsFor<N>\` return type is required: attaching \`.rich\` / \`.markup\`
 * otherwise widens \`K\` to the full key union and ICU args become a union (excess-property
 * checks turn off, so wrong value types stop erroring).
 *
 * \`t\` / \`markup\` return \`TranslatedText\` (opaque brand); plain string literals are not
 * assignable. \`.rich\` stays \`ReactNode\`.
 */
export function useTranslations<N extends Namespace>(
  namespace: N,
): TranslationsFor<N> {
  const translator = useCatalogTranslations(namespace);

  function t<K extends MessageKeyOf<N>>(
    key: K,
    ...args: TranslateValuesArgs<MessageArgsOf<N, K>>
  ): TranslatedText {
    return brandTranslatedText(translator(key, ...args));
  }

  t.rich = <K extends MessageKeyOf<N>>(
    key: K,
    ...args: TranslateValuesArgs<MessageArgsOf<N, K>>
  ): ReactNode => translator.rich(key, ...args);

  t.markup = <K extends MessageKeyOf<N>>(
    key: K,
    ...args: TranslateValuesArgs<MessageArgsOf<N, K>>
  ): TranslatedText => brandTranslatedText(translator.markup(key, ...args));

  t.raw = <K extends MessageKeyOf<N>>(key: K): unknown => translator.raw(key);

  t.has = <K extends MessageKeyOf<N>>(key: K): boolean => translator.has(key);

  return t;
}
`;
}

export interface TranslationGeneratorOptions {
  /** Emit per-locale bundles under i18n/locales/ (default: single i18n/messages.ts). */
  splitLocaleBundles?: boolean;
  /**
   * Emit a request config that reads the `plumbus-ui-locale` cookie server-side
   * (after `requestLocale`) so Server Components render the correct locale on first
   * paint. Opt-in because reading the cookie uses a Next.js Dynamic API, which opts
   * routes into dynamic rendering and is unsupported under `output: 'export'`.
   * Default: the request config resolves locale from `requestLocale` only.
   */
  serverLocaleCookie?: boolean;
}

/**
 * Resolve the shared default locale for generated config.
 * All namespaces must agree — the UI catalog indexes Messages by one defaultLocale.
 */
function resolveSharedDefaultLocale(definitions: TranslationDefinition[]): string {
  const first = definitions[0]?.defaultLocale ?? 'en';
  for (const def of definitions) {
    if (def.defaultLocale !== first) {
      throw new Error(
        `Translation namespaces must share the same defaultLocale for UI generate ` +
          `(got "${first}" from "${definitions[0]?.name ?? 'unknown'}" and ` +
          `"${def.defaultLocale}" from "${def.name}")`,
      );
    }
  }
  return first;
}

/**
 * Generate all i18n module files from discovered translation definitions.
 */
export function generateTranslationModule(
  definitions: TranslationDefinition[],
  options: TranslationGeneratorOptions = {},
): GeneratedTranslationFile[] {
  if (definitions.length === 0) return [];

  const defaultLocale = resolveSharedDefaultLocale(definitions);

  const catalog = buildMessageCatalog(definitions);
  const locales = Object.keys(catalog);

  const files: GeneratedTranslationFile[] = [];

  if (options.splitLocaleBundles) {
    for (const locale of locales) {
      const localeCatalog = catalog[locale];
      if (localeCatalog === undefined) continue;
      files.push({
        path: `i18n/locales/${locale}.ts`,
        content: generateSplitLocaleBundle(localeCatalog),
      });
    }
    files.push({
      path: 'i18n/messages.ts',
      content: generateSplitMessagesAggregator(locales, defaultLocale),
    });
  } else {
    files.push({
      path: 'i18n/messages.ts',
      content: generateMessagesCatalog(definitions),
    });
  }

  files.push(
    { path: 'i18n/config.ts', content: generateConfig(definitions) },
    { path: 'i18n/keys.ts', content: generateKeysModule() },
    { path: 'i18n/translated-text.ts', content: generateTranslatedTextModule() },
    { path: 'i18n/global.ts', content: generateNextIntlAugmentation() },
    { path: 'i18n/request.ts', content: generateRequestConfig(options.serverLocaleCookie) },
    { path: 'i18n/provider.tsx', content: generateProvider() },
    { path: 'i18n/index.ts', content: generateUseTranslation() },
  );

  return files;
}
