export const EDITABLE_HEADER = `// Generated by plumbus browser-extension scaffold.
// This file is owned by your app after generation and may be edited.
`;

export const REGENERATED_CLIENT_HEADER = `// Generated by plumbus browser-extension scaffold.
// Do not edit manually. Re-run the scaffold command after capability changes.
`;

export function apiOrigin(apiBaseUrl: string): string {
  return new URL(apiBaseUrl).origin;
}

export function hostPermission(apiBaseUrl: string): string {
  return `${apiOrigin(apiBaseUrl)}/*`;
}
