import type { BrowserExtensionScaffoldConfig, GeneratedFile } from '../types.js';
import { hostPermission } from './constants.js';

export function generateWxtConfig(config: BrowserExtensionScaffoldConfig): GeneratedFile {
  const host = hostPermission(config.apiBaseUrl);
  const hostPermJson = JSON.stringify(host);
  const hostPermsArrayJson = JSON.stringify([host]);
  const browsers = config.browsers ?? ['chrome', 'firefox'];
  const browserComment =
    browsers.length === 2
      ? 'Chrome (MV3 host_permissions) and Firefox (MV2 permissions) via dev:firefox / build:firefox'
      : `Target browser: ${browsers.join(', ')}`;
  return {
    path: 'wxt.config.ts',
    content: `${EDITABLE_HEADER_IMPORT}import { defineConfig } from 'wxt';

// ${browserComment}
// WXT targets Firefox with Manifest V2 — host_permissions is MV3-only; branch on manifestVersion.
export default defineConfig({
  modules: ['@wxt-dev/module-react'],
  manifest: ({ manifestVersion }) => ({
    name: '${escapeJs(config.appName)}',
    permissions:
      manifestVersion === 2 ? ['storage', ${hostPermJson}] : ['storage'],
    host_permissions: manifestVersion === 2 ? [] : ${hostPermsArrayJson},
  }),
});
`,
  };
}

const EDITABLE_HEADER_IMPORT = `// Generated by plumbus browser-extension scaffold.
// This file is owned by your app after generation and may be edited.

`;

function escapeJs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
